dist: trusty
sudo: false
script: make
env:
  - CXX='clang++-4.0 -std=c++11' CC=clang-4.0
  - CXX=g++-6 CC=gcc-6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-4.0
    packages:
    - gcc-6
    - g++-6
    - cmake
    - libboost-all-dev
    - clang-4.0
